#!/usr/bin/env ruby

$LOAD_PATH << "lib"
$LOAD_PATH << "models"

require 'environment'
Environment.environment = ENV["ENVIRONMENT"] || "production"

require 'journal'
require 'person'

require 'date'
require 'time'

$stderr = $stdout

def menu
<<EOS
What do you want to do?
1. Add person.
2. Tell me a story.
3. Display 5 most recent entries.
4. Search for an entry by date.
5. Search all entries.
6. Exit the app.
EOS
end

def get_menu_selection
  puts menu
  input = gets
  return unless input
  input.chomp!
  if input == "1"
    add_person
  elsif input == "2"
    add_journal_entry
  elsif input == "3"
    Journal.display_most_recent
    puts "\n"
    get_menu_selection
  elsif input == "4"
    print "Please enter a date (in the format 2014-05-08): "
    Journal.display_by_date(gets.chomp)
    puts "\n"
    get_menu_selection
  elsif input == "5"
    print "Please enter the text you would like to search for: "
    Journal.display_by_search(gets.chomp)
    puts "\n"
    get_menu_selection
  elsif input == "6"
    puts "Thank you for using Doogie Howser, CLI. Have a great day!"
    exit
  else
    puts "'#{input}' is not a valid selection."
    get_menu_selection
  end
end

def add_person
  puts "What is your name?"
  person_name = gets
  return unless person_name
  person_name.chomp!
  person = Person.new(person_name)
  if person.save
    puts "Hi, #{person.name}! Welcome to Doogie Howser, CLI."
  else
    puts person.errors
    add_person
  end
  puts "\n"
  get_menu_selection
end

def add_journal_entry
  puts "Tell me a story."
  print current_datetime
  journal_entry = gets.chomp
  journal = Journal.new(journal_entry)
  if journal.save
    puts "Your journal entry has been saved!"
  else
    puts journal.errors
    add_journal_entry
  end
  puts "\n"
  get_menu_selection
end

def current_datetime
  now = DateTime.now
  now_string = now.strftime('%A, %B %d, %Y, %I:%M%p ... ')
  return now_string
end

get_menu_selection
